sudo: false
language: scala
scala:
- 2.12.7
- 2.11.12
before_cache:
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.coursier/cache"
  - "$HOME/.sbt"
jdk:
- oraclejdk8
script:
- sbt ++$TRAVIS_SCALA_VERSION test it:test
env:
  global:
  - secure: N4XoGsLApmCk2dLZiAbULCafk65tfpuMHbkxvIQF6flfszILgeM/UCmtl/QIIOwlhJqG8a7By3YRjkDgsTDvB7H+2qt6PykmiPAymL+9ipo5KX1T201MIIrzPELkHtJbEkupe+BN34/uw/xIphw2PpcfmXBERAS0H2EY0t/HYBRxaihmwad1aMC0tVnBSoX9KFn5Dn+OpWdkow0CeO/CQ5TJqYudn+CPs7dq7mNZypfqqlUMLjbLcxmTuI5Gm24lF1s2IW1SYQ2wxgnrit9RwuiT7CRYgbJfBaGyZpZCgF8ZHOAISd1j5CSIAIItji9pzobkHbh6Xjk4qEkE0LNSGoGFiXMFfTHdNgG+jMfCMu2ffuBh//VWzYJZM8kHAy9Idu2CLmee7ZsM2GAER8KuT31NB0QwSZCDBIibLNDORVsHcI28UDhnhM5Vkg2R7HxScLR8kP+ZGwqslJe3cIgGWZ4CsiLAarFqltfubuI8mkj4Ga4x32TecriYCgbX8CteOddU+N5PrYyFfJjG37Nk3LOvfQDEaa6BeVX4sCLtXvYNuOg4MW4uYsrFMyyd049nP3zaw4JicAyosxRnLSjw+VhroQo3PEti61D+V6nAp0bc8rMDUmTJWGQke+7JVhYZHgXDvd98neJ1trwqJ7TE14nJO7hCLefW0SozPMFrcLA=
  - secure: PmTowwtY9Yy+yrV3e8kiJwkVso50VfLyeKkcyc5+snrCnw5Q1vvB0J1z3H7V13P4ycil3rh4+KPGOMvV67RWdFwMlQOv9zdlK9rtzOZW315FhMhsQCd6ZD/XvRXP9t++H6ZX1yfS77WvZAAhpP93p8ht3G9rVqIVmbYd4QwhDg6JvnugeSIXGGjSawR8ZvlspvbJ+COz9S/kXePlhEMdxRKLTeBkN4ID5jZnmGhSl35Kg9IOy72aCRfGKn56O8TTo7zR0RE/l8EGhQX0VuF6ejFs6+vGUULOn4pUPRusI9sISq2B8xcyGVa4kzFo5/DXrxd08YD5eI3C5OhhYHf1VcOkGB2u0olnpLvioU8NH6gCvg88F6gUkHLPh0l7841EHCblz0y/Qb5G1mYdXdudm8lenBqUZ1DZmtpgpFY8D+I1eBEFXNI3H+zP5UDXhbR/o0Fgy67Srhv2hhUeRpNO3FzdmfEk0xaPVfb1Yny4sbuSSFvfu4WaEfjtgdVR6wpwlyV1QmFNYLC1O5bMjeYa/1CDdRg2ArXnDYCCDZLMO2QviXmVtI61FW5iRX7ROf77cdaS6wI/SMiffLzuW5x1cg0T939fp/iDgixh67frq0DN/SZX2HSNPpYUmRJWr128cUldVzaz1oa6YVBccpkaEtXf3sqRIzc74co11ctqMYI=
  - secure: CeUEg2A3sC6rt62mPVpMxbWsNv15sjpVhEDctds/hq8/hw6W7FuL994CxhO8ow0BD9zaldSKlUUQ59K1qaBR3ZjpmTv35H7MkkiDyQyp+p7Zu4Q3p02Hi3cMKM8uhhA4dxS1XSpAVHpBg8E51no9Sen3x0dYNV+ZeDiAclOvd/1t9uXorcf764Bq+FwJZr5GnjIpdr+YWPNwemVmqXo8Mvm8jkWUbjwHv1Fe28Cb9WP1ftihE3Q53ZxVJwSXYrXgf7HKGjvZMD6EjhPR9gGwa7IA0qG6+3iihqr4n2tiWQ+YgTw88GfLM1hGrGUb3vREJf+rqz08Hww8jdQmdmF9yBK0nJ6OprtERPprOnuT+uOh8iO5MKDB/7TaVHoyNY1EgySBaJvjqE0ZRFum1DBT/GCZ09lRtK4MdZJzY0fg1KRyE6PnVehts/ri79vbpUDvEzZgWiYPZSlF/SPcvUKBCXiYBH/mF36/Z9BAwCGvSBFqufTY/xnhpInk9abhwYvnB+pl7o1wXMjSTi/liJ1qEL4k3aXkI7YEocZiEQqzgv93MKvqOiJCMlw9B0Bln7ADLLJeB59g4eY7rVwO9EWpHFqKQquJtWs2xoY8GI3RkfSIxNpnxPKoHsSHeEjNr8e3+6aPHqMpcthXV27bYpf8MxRPSRmlgpiV6mrfvbtprpY=
